<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>CryptoSmithX.Studio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoSmithX.Database\CryptoSmithX.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Sentry.AspNetCore" Version="6.9.0" />
  </ItemGroup>

</Project>
