<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <RootNamespace>CryptoSmithX.MarketData.Hub</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoSmithX.MarketData.Connectors\CryptoSmithX.MarketData.Connectors.csproj" />
    <ProjectReference Include="..\CryptoSmithX.Database\CryptoSmithX.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoSmithX.MarketData.Hub.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Sentry.Extensions.Logging" Version="6.9.0" />
  </ItemGroup>
</Project>
