#!/usr/bin/env python3
"""Rebuild marks/index.json from the files on disk, and refuse to write a bad one.

Run it after adding, replacing or deleting a mark:

    python3 marks/tools/index.py            # check and rewrite index.json
    python3 marks/tools/index.py --check     # check only, non-zero exit if stale or broken

The index exists for one reason: a page has to know whether a mark is there BEFORE it asks
for it. Probing with <img onerror> means the reader sees a broken image first, and a broken
image is the dishonest failure this whole feature is written to avoid.

Standard library only. No network, no npm.
"""
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KINDS = ("venue", "asset")
VARIANTS = ("branded", "mono")
GEOMETRY = {"path", "circle", "rect", "ellipse", "polygon", "polyline", "line", "use"}


def check(path):
    """Every reason we would refuse to ship a file. Returns a list of complaints."""
    bad = []
    raw = open(path, encoding="utf-8").read()
    try:
        root = ET.fromstring(raw)
    except ET.ParseError as e:
        return ["does not parse as XML: %s" % e]

    if root.tag.split("}")[-1] != "svg":
        bad.append("root element is not <svg>")
    if "viewBox" not in root.attrib:
        bad.append("no viewBox — it cannot be scaled into a slot")

    tags = [el.tag.split("}")[-1] for el in root.iter()]
    if not any(t in GEOMETRY for t in tags):
        bad.append("no geometry: nothing in it draws anything")
    drawn = sum(len(el.attrib.get("d", "")) + len(el.attrib.get("points", "")) for el in root.iter())
    shapes = sum(1 for t in tags if t in ("circle", "rect", "ellipse"))
    if drawn < 20 and shapes == 0:
        bad.append("geometry is empty or trivial (%d chars of path data)" % drawn)
    for t in ("script", "foreignObject", "image"):
        if t in tags:
            bad.append("contains <%s>" % t)

    # Nothing may reach off this repository at render time. House rule: no CDN, ever.
    for ref in re.findall(r'(?:href|xlink:href|src)="([^"]+)"', raw):
        if not ref.startswith("#"):
            bad.append("external reference: %s" % ref)
    for ref in re.findall(r"url\(([^)]*)\)", raw):
        if not ref.strip().strip("'\"").startswith("#"):
            bad.append("external url(): %s" % ref)
    if "@import" in raw:
        bad.append("contains @import")
    stripped = raw.replace("http://www.w3.org", "").replace("https://www.w3.org", "")
    if "http://" in stripped or "https://" in stripped:
        bad.append("mentions a remote URL")

    variant = os.path.basename(os.path.dirname(path))
    if variant == "mono":
        if "currentColor" not in raw:
            bad.append("mono file with no currentColor: it cannot take the page's ink")
        for c in re.findall(r'(?:fill|stroke)="([^"]+)"', raw):
            if c.strip() not in ("none", "currentColor"):
                bad.append("mono file carries a hard colour: %s" % c)
    return bad


def main():
    check_only = "--check" in sys.argv
    index = {
        "$comment": "Generated by tools/index.py from the files on disk - do not hand-edit. "
                    "A page reads this to know whether a mark exists before it asks for one; "
                    "that is what keeps a missing mark from becoming a broken image.",
        "generated": None,
    }
    problems, total, size = [], 0, 0
    for kind in KINDS:
        index[kind] = {}
        for variant in VARIANTS:
            d = os.path.join(ROOT, kind, variant)
            keys = []
            for name in sorted(os.listdir(d)) if os.path.isdir(d) else []:
                if not name.endswith(".svg"):
                    problems.append("%s/%s/%s is not an .svg" % (kind, variant, name))
                    continue
                p = os.path.join(d, name)
                for c in check(p):
                    problems.append("%s/%s/%s: %s" % (kind, variant, name, c))
                keys.append(name[:-4])
                total += 1
                size += os.path.getsize(p)
            index[kind][variant] = keys

    old = {}
    ipath = os.path.join(ROOT, "index.json")
    if os.path.exists(ipath):
        old = json.load(open(ipath))
    index["generated"] = old.get("generated") if check_only else __import__("datetime").date.today().isoformat()

    stale = any(old.get(k, {}).get(v) != index[k][v] for k in KINDS for v in VARIANTS)
    for p in problems:
        print("BROKEN  " + p)
    if check_only:
        if stale:
            print("STALE   index.json does not match the files on disk — run tools/index.py")
        print("%d files, %d bytes, %d problems" % (total, size, len(problems)))
        sys.exit(1 if problems or stale else 0)

    if problems:
        print("refusing to write index.json while %d files are broken" % len(problems))
        sys.exit(1)
    open(ipath, "w").write(json.dumps(index, indent=1) + "\n")
    print("index.json written: %d files, %d bytes" % (total, size))
    print("  " + ", ".join("%s/%s %d" % (k, v, len(index[k][v])) for k in KINDS for v in VARIANTS))


if __name__ == "__main__":
    main()
